"""add_warehouse_operating_hours

Revision ID: 6d1b9ce22183
Revises: b8041c309aec
Create Date: 2026-03-23 12:58:59.385332+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1b9ce22183'
down_revision: Union[str, None] = 'b8041c309aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses_operating_hours',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('day_of_the_week', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.CheckConstraint('NOT is_open OR (open_time IS NOT NULL AND close_time IS NOT NULL)', name='ck_warehouse_hours_when_open'),
    sa.CheckConstraint('NOT is_open OR open_time < close_time', name='ck_warehouse_hours_order'),
    sa.CheckConstraint('day_of_the_week >= 0 AND day_of_the_week <= 6', name='ck_warehouse_day_range'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'day_of_the_week', name='uq_warehouse_day')
    )
    op.create_index('ix_warehouses_operating_hours_warehouse', 'warehouses_operating_hours', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_warehouses_operating_hours_warehouse', table_name='warehouses_operating_hours')
    op.drop_table('warehouses_operating_hours')
    # ### end Alembic commands ###
