"""add_tenant_plan_and_max_users

Revision ID: 3e14facaed1b
Revises: 70e5a3657370
Create Date: 2026-03-04 12:25:13.008095+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e14facaed1b'
down_revision: Union[str, None] = '70e5a3657370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('plan', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('max_users', sa.Integer(), nullable=False))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tenants', 'max_users')
    op.drop_column('tenants', 'plan')
    # ### end Alembic commands ###
