"""add_tenant_slug

Revision ID: 70e5a3657370
Revises: 7869232d620d
Create Date: 2026-03-03 18:00:40.836415+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e5a3657370'
down_revision: Union[str, None] = '7869232d620d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'tenants', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'slug')
    # ### end Alembic commands ###
