"""initial_models

Revision ID: 7869232d620d
Revises: 
Create Date: 2026-03-03 15:57:13.588800+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7869232d620d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_tenants_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenants_active_name', 'tenants', ['is_active', 'name'], unique=False)
    op.create_table('trailers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('trailer_type', postgresql.ENUM('STANDARD', 'REFRIGERATED', 'FLATBED', 'TANKER', name='trailer_type'), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('capacity_m3', sa.Float(), nullable=True),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'ATTACHED', 'MAINTENANCE', 'INACTIVE', name='trailer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_kg IS NULL OR capacity_kg > 0', name='ck_trailers_capacity_kg_positive'),
    sa.CheckConstraint('capacity_m3 IS NULL OR capacity_m3 > 0', name='ck_trailers_capacity_m3_positive'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trailers_tenant_id'), 'trailers', ['tenant_id'], unique=False)
    op.create_index('ix_trailers_tenant_plate_unique', 'trailers', ['tenant_id', 'plate_number'], unique=True)
    op.create_index('ix_trailers_tenant_status', 'trailers', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_trailers_tenant_type_status', 'trailers', ['tenant_id', 'trailer_type', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MANAGER', 'DISPATCHER', 'DRIVER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email LIKE '%%@%%.%%'", name='ck_users_email_format'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_active_google', 'users', ['tenant_id', 'google_id'], unique=False, postgresql_where='is_active = true AND google_id IS NOT NULL')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('ix_users_tenant_active', 'users', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_users_tenant_email_unique', 'users', ['tenant_id', 'email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', postgresql.ENUM('TRUCK', 'VAN', 'OTHER', name='vehicle_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'ON_ROUTE', 'MAINTENANCE', 'INACTIVE', 'RESERVED', name='vehicle_status'), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('last_position_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_latitude IS NULL OR (current_latitude >= -90 AND current_latitude <= 90)', name='ck_vehicles_latitude_range'),
    sa.CheckConstraint('current_longitude IS NULL OR (current_longitude >= -180 AND current_longitude <= 180)', name='ck_vehicles_longitude_range'),
    sa.CheckConstraint('year IS NULL OR (year >= 1900 AND year <= EXTRACT(YEAR FROM CURRENT_DATE) + 1)', name='ck_vehicles_year_range'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicles_tenant_available', 'vehicles', ['tenant_id', 'vehicle_type'], unique=False, postgresql_where="status = 'AVAILABLE'")
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_index('ix_vehicles_tenant_plate_unique', 'vehicles', ['tenant_id', 'plate_number'], unique=True)
    op.create_index('ix_vehicles_tenant_status', 'vehicles', ['tenant_id', 'status'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('warehouse_type', postgresql.ENUM('WAREHOUSE', 'CLIENT', 'PICKUP_POINT', name='warehouse_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_warehouses_latitude_range'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_warehouses_name_not_empty'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_warehouses_longitude_range'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warehouses_active', 'warehouses', ['tenant_id', 'warehouse_type'], unique=False, postgresql_where='is_active = true')
    op.create_index('ix_warehouses_tenant_active', 'warehouses', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_warehouses_tenant_id'), 'warehouses', ['tenant_id'], unique=False)
    op.create_index('ix_warehouses_tenant_type', 'warehouses', ['tenant_id', 'warehouse_type'], unique=False)
    op.create_table('driver_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.CheckConstraint("license_expiry IS NULL OR license_expiry > '1900-01-01'", name='ck_driver_profiles_license_expiry_valid'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_driver_profiles_tenant_id'), 'driver_profiles', ['tenant_id'], unique=False)
    op.create_index('ix_driver_profiles_tenant_license', 'driver_profiles', ['tenant_id', 'license_number'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('origin_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_contact', sa.String(length=255), nullable=True),
    sa.Column('cargo_description', sa.String(length=500), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', 'FAILED', 'RETURNED', name='order_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.CheckConstraint('length(trim(order_number)) > 0', name='ck_orders_number_not_empty'),
    sa.CheckConstraint('origin_warehouse_id != destination_warehouse_id', name='ck_orders_different_warehouses'),
    sa.CheckConstraint('volume_m3 IS NULL OR volume_m3 > 0', name='ck_orders_volume_positive'),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0', name='ck_orders_weight_positive'),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_active', 'orders', ['tenant_id', 'status'], unique=False, postgresql_where="status IN ('PENDING', 'ASSIGNED', 'IN_TRANSIT')")
    op.create_index(op.f('ix_orders_destination_warehouse_id'), 'orders', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_orders_origin_warehouse_id'), 'orders', ['origin_warehouse_id'], unique=False)
    op.create_index('ix_orders_tenant_created', 'orders', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index('ix_orders_tenant_number_unique', 'orders', ['tenant_id', 'order_number'], unique=True)
    op.create_index('ix_orders_tenant_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trailer_id', sa.UUID(), nullable=True),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='trip_status'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_arrival IS NULL OR actual_departure IS NULL OR actual_arrival > actual_departure', name='ck_trips_actual_times_order'),
    sa.CheckConstraint('planned_arrival > planned_departure', name='ck_trips_planned_times_order'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trailer_id'], ['trailers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trips_active', 'trips', ['tenant_id', 'driver_id', 'vehicle_id'], unique=False, postgresql_where="status IN ('PLANNED', 'IN_PROGRESS')")
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_order_id'), 'trips', ['order_id'], unique=True)
    op.create_index('ix_trips_tenant_driver', 'trips', ['tenant_id', 'driver_id'], unique=False)
    op.create_index(op.f('ix_trips_tenant_id'), 'trips', ['tenant_id'], unique=False)
    op.create_index('ix_trips_tenant_status', 'trips', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_trips_tenant_vehicle', 'trips', ['tenant_id', 'vehicle_id'], unique=False)
    op.create_index(op.f('ix_trips_trailer_id'), 'trips', ['trailer_id'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('work_times',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_type', postgresql.ENUM('DRIVING', 'REST', 'LOADING', 'WAITING', 'BREAK', 'OTHER', name='work_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at > started_at', name='ck_work_times_times_order'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_times_driver_id'), 'work_times', ['driver_id'], unique=False)
    op.create_index('ix_work_times_driver_started', 'work_times', ['driver_id', 'started_at'], unique=False)
    op.create_index('ix_work_times_open', 'work_times', ['tenant_id', 'driver_id'], unique=False, postgresql_where='ended_at IS NULL')
    op.create_index('ix_work_times_tenant_driver', 'work_times', ['tenant_id', 'driver_id'], unique=False)
    op.create_index(op.f('ix_work_times_tenant_id'), 'work_times', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_times_trip_id'), 'work_times', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_times_trip_id'), table_name='work_times')
    op.drop_index(op.f('ix_work_times_tenant_id'), table_name='work_times')
    op.drop_index('ix_work_times_tenant_driver', table_name='work_times')
    op.drop_index('ix_work_times_open', table_name='work_times', postgresql_where='ended_at IS NULL')
    op.drop_index('ix_work_times_driver_started', table_name='work_times')
    op.drop_index(op.f('ix_work_times_driver_id'), table_name='work_times')
    op.drop_table('work_times')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_trailer_id'), table_name='trips')
    op.drop_index('ix_trips_tenant_vehicle', table_name='trips')
    op.drop_index('ix_trips_tenant_status', table_name='trips')
    op.drop_index(op.f('ix_trips_tenant_id'), table_name='trips')
    op.drop_index('ix_trips_tenant_driver', table_name='trips')
    op.drop_index(op.f('ix_trips_order_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index('ix_trips_active', table_name='trips', postgresql_where="status IN ('PLANNED', 'IN_PROGRESS')")
    op.drop_table('trips')
    op.drop_index('ix_orders_tenant_status', table_name='orders')
    op.drop_index('ix_orders_tenant_number_unique', table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index('ix_orders_tenant_created', table_name='orders')
    op.drop_index(op.f('ix_orders_origin_warehouse_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_destination_warehouse_id'), table_name='orders')
    op.drop_index('ix_orders_active', table_name='orders', postgresql_where="status IN ('PENDING', 'ASSIGNED', 'IN_TRANSIT')")
    op.drop_table('orders')
    op.drop_index('ix_driver_profiles_tenant_license', table_name='driver_profiles')
    op.drop_index(op.f('ix_driver_profiles_tenant_id'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index('ix_warehouses_tenant_type', table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_tenant_id'), table_name='warehouses')
    op.drop_index('ix_warehouses_tenant_active', table_name='warehouses')
    op.drop_index('ix_warehouses_active', table_name='warehouses', postgresql_where='is_active = true')
    op.drop_table('warehouses')
    op.drop_index('ix_vehicles_tenant_status', table_name='vehicles')
    op.drop_index('ix_vehicles_tenant_plate_unique', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_index('ix_vehicles_tenant_available', table_name='vehicles', postgresql_where="status = 'AVAILABLE'")
    op.drop_table('vehicles')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('ix_users_tenant_email_unique', table_name='users')
    op.drop_index('ix_users_tenant_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_active_google', table_name='users', postgresql_where='is_active = true AND google_id IS NOT NULL')
    op.drop_table('users')
    op.drop_index('ix_trailers_tenant_type_status', table_name='trailers')
    op.drop_index('ix_trailers_tenant_status', table_name='trailers')
    op.drop_index('ix_trailers_tenant_plate_unique', table_name='trailers')
    op.drop_index(op.f('ix_trailers_tenant_id'), table_name='trailers')
    op.drop_table('trailers')
    op.drop_index('ix_tenants_active_name', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
